import type { Metadata } from "next";
import { Inter, Bitter, Montserrat, Raleway, Nunito, Roboto_Flex } from "next/font/google";
import "./globals.css";
import { Layout } from "@/components/layout/Layout";

const inter = Inter({ subsets: ["latin"] });
const alexandria = Roboto_Flex({ subsets: ["latin"] });
const andika = Bitter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body className={alexandria.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
